import * as React from 'react'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import './globals.css'

import { Toaster } from '@/components/ui/sonner'
import { CookieConsent } from '@/components/cookie-consent'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { VercelAnalytics } from '@/components/vercel-analytics'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {children}
          <Toaster richColors closeButton />
          <CookieConsent />
        </SessionProvider>
        <TailwindIndicator />
        <VercelAnalytics />
      </body>
    </html>
  )
}
