import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Analytics } from '@vercel/analytics/react'
import './globals.css'

import { Toaster } from '@/components/ui/sonner'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { CookieConsent } from '@/components/cookie-consent'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {children}
          <Toaster richColors closeButton />
          <CookieConsent />
        </SessionProvider>
        {process.env.NODE_ENV !== 'production' ? <TailwindIndicator /> : null}
        {process.env.NODE_ENV === 'production' ? <Analytics /> : null}
      </body>
    </html>
  )
}
